const countries = [
  { name: "Afghanistan", abbrv: "Afghanistan" },
  { name: "Albania", abbrv: "Albania" },
  { name: "Algeria", abbrv: "Algeria" },
  { name: "Andorra", abbrv: "Andorra" },
  { name: "Angola", abbrv: "Angola" },
  { name: "Antigua and Barbuda", abbrv: "Antigua-and-Barbuda" },
  { name: "Argentina", abbrv: "Argentina" },
  { name: "Armenia", abbrv: "Armenia" },
  { name: "Aruba", abbrv: "Aruba" },
  { name: "Australia", abbrv: "Australia" },
  { name: "Austria", abbrv: "Austria" },
  { name: "Azerbaijan", abbrv: "Azerbaijan" },
  { name: "Bahamas", abbrv: "Bahamas" },
  { name: "Bahrain", abbrv: "Bahrain" },
  { name: "Bangladesh", abbrv: "Bangladesh" },
  { name: "Barbados", abbrv: "Barbados" },
  { name: "Belarus", abbrv: "Belarus" },
  { name: "Belgium", abbrv: "Belgium" },
  { name: "Benin", abbrv: "Benin" },
  { name: "Bermuda", abbrv: "Bermuda" },
  { name: "Bhutan", abbrv: "Bhutan" },
  { name: "Brazil", abbrv: "Brazil" },
  { name: "Brunei", abbrv: "Brunei-" },
  { name: "Bulgaria", abbrv: "Bulgaria" },
  { name: "Burkina Faso", abbrv: "Burkina-Faso" },
  { name: "Cabo Verde", abbrv: "Cabo-Verde" },
  { name: "Cambodia", abbrv: "Cambodia" },
  { name: "Cameroon", abbrv: "Cameroon" },
  { name: "Canada", abbrv: "Canada" },
  { name: "Cayman Islands", abbrv: "Cayman-Islands" },
  { name: "Central African Republic", abbrv: "CAR" },
  { name: "Chad", abbrv: "Chad" },
  { name: "Channel Islands", abbrv: "Channel-Islands" },
  { name: "Chile", abbrv: "Chile" },
  { name: "China", abbrv: "China" },
  { name: "Colombia", abbrv: "Colombia" },
  { name: "Congo", abbrv: "Congo" },
  { name: "Costa Rica", abbrv: "Costa-Rica" },
  { name: "Croatia", abbrv: "Croatia" },
  { name: "Cuba", abbrv: "Cuba" },
  { name: "Curacao", abbrv: "Cura&ccedil;ao" },
  { name: "Cyprus", abbrv: "Cyprus" },
  { name: "Czechia", abbrv: "Czechia" },
  { name: "Democratic Republic of the Congo", abbrv: "DRC" },
  { name: "Denmark", abbrv: "Denmark" },
  { name: "Djibouti", abbrv: "Djibouti" },
  { name: "Dominican Republic", abbrv: "Dominican-Republic" },
  { name: "Ecuador", abbrv: "Ecuador" },
  { name: "Egypt", abbrv: "Egypt" },
  { name: "El Salvador", abbrv: "El-Salvador" },
  { name: "Equatorial Guinea", abbrv: "Equatorial-Guinea" },
  { name: "Eritrea", abbrv: "Eritrea" },
  { name: "Estonia", abbrv: "Estonia" },
  { name: "Eswatini", abbrv: "Eswatini" },
  { name: "Ethiopia", abbrv: "Ethiopia" },
  { name: "Faeroe Islands", abbrv: "Faeroe-Islands" },
  { name: "Fiji", abbrv: "Fiji" },
  { name: "Finland", abbrv: "Finland" },
  { name: "France", abbrv: "France" },
  { name: "French Guinea", abbrv: "French-Guinea" },
  { name: "French Polynesia", abbrv: "French-Polynesia" },
  { name: "Gabon", abbrv: "Gabon" },
  { name: "Gambia", abbrv: "Gambia" },
  { name: "Georgia", abbrv: "Georgia" },
  { name: "Germany", abbrv: "Germany" },
  { name: "Ghana", abbrv: "Ghana" },
  { name: "Gibraltar", abbrv: "Gibraltar" },
  { name: "Greece", abbrv: "Greece" },
  { name: "Greenland", abbrv: "Greenland" },
  { name: "Guadeloupe", abbrv: "Guadeloupe" },
  { name: "Guam", abbrv: "Guam" },
  { name: "Guatemala", abbrv: "Guatemala" },
  { name: "Guinea", abbrv: "Guinea" },
  { name: "Guyana", abbrv: "Guyana" },
  { name: "Haiti", abbrv: "Haiti" },
  { name: "Honduras", abbrv: "Honduras" },
  { name: "Hong Kong", abbrv: "Hong-Kong" },
  { name: "Hungary", abbrv: "Hungary" },
  { name: "Iceland", abbrv: "Iceland" },
  { name: "India", abbrv: "India" },
  { name: "Indonesia", abbrv: "Indonesia" },
  { name: "Iran", abbrv: "Iran" },
  { name: "Iraq", abbrv: "Iraq" },
  { name: "Ireland", abbrv: "Ireland" },
  { name: "Isle of Man", abbrv: "Isle-of-Man" },
  { name: "Israel", abbrv: "Israel" },
  { name: "Italy", abbrv: "Italy" },
  { name: "Ivory Coast", abbrv: "Ivory-Coast" },
  { name: "Jamaica", abbrv: "Jamaica" },
  { name: "Japan", abbrv: "Japan" },
  { name: "Jordan", abbrv: "Jordan" },
  { name: "Kazakhstan", abbrv: "Kazakhstan" },
  { name: "Kenya", abbrv: "Kenya" },
  { name: "Kuwait", abbrv: "Kuwait" },
  { name: "Kyrgyzstan", abbrv: "Kyrgyzstan" },
  { name: "Latvia", abbrv: "Latvia" },
  { name: "Lebanon", abbrv: "Lebanon" },
  { name: "Liberia", abbrv: "Liberia" },
  { name: "Liechtenstein", abbrv: "Liechtenstein" },
  { name: "Lithuania", abbrv: "Lithuania" },
  { name: "Luxembourg", abbrv: "Luxembourg" },
  { name: "Macao", abbrv: "Macao" },
  { name: "Madagascar", abbrv: "Madagascar" },
  { name: "Malaysia", abbrv: "Malaysia" },
  { name: "Maldives", abbrv: "Maldives" },
  { name: "Malta", abbrv: "Malta" },
  { name: "Martinique", abbrv: "Martinique" },
  { name: "Mauritania", abbrv: "Mauritania" },
  { name: "Mauritius", abbrv: "Mauritius" },
  { name: "Mayotte", abbrv: "Mayotte" },
  { name: "Mexico", abbrv: "Mexico" },
  { name: "Moldova", abbrv: "Moldova" },
  { name: "Monaco", abbrv: "Monaco" },
  { name: "Mongolia", abbrv: "Mongolia" },
  { name: "Montenegro", abbrv: "Montenegro" },
  { name: "Montserrat", abbrv: "Montserrat" },
  { name: "Morocco", abbrv: "Morocco" },
  { name: "Namibia", abbrv: "Namibia" },
  { name: "Nepal", abbrv: "Nepal" },
  { name: "Netherlands", abbrv: "Netherlands" },
  { name: "New Caledonia", abbrv: "New-Caledonia" },
  { name: "New Zealand", abbrv: "New-Zealand" },
  { name: "Nicaragua", abbrv: "Nicaragua" },
  { name: "Niger", abbrv: "Niger" },
  { name: "Nigeria", abbrv: "Nigeria" },
  { name: "North Macedonia", abbrv: "North-Macedonia" },
  { name: "Norway", abbrv: "Norway" },
  { name: "Oman", abbrv: "Oman" },
  { name: "Pakistan", abbrv: "Pakistan" },
  { name: "Palestine", abbrv: "Palestine" },
  { name: "Panama", abbrv: "Panama" },
  { name: "Papua New Guinea", abbrv: "Papua-New-Guinea" },
  { name: "Paraguay", abbrv: "Paraguay" },
  { name: "Peru", abbrv: "Peru" },
  { name: "Philippines", abbrv: "Philippines" },
  { name: "Poland", abbrv: "Poland" },
  { name: "Portugal", abbrv: "Portugal" },
  { name: "Puerto Rico", abbrv: "Puerto-Rico" },
  { name: "Qatar", abbrv: "Qatar" },
  { name: "Reunion", abbrv: "R&eacute;union" },
  { name: "Romania", abbrv: "Romania" },
  { name: "Russia", abbrv: "Russia" },
  { name: "Rwanda", abbrv: "Rwanda" },
  { name: "South Korea", abbrv: "S.-Korea" },
  { name: "Saint Lucia", abbrv: "Saint-Lucia" },
  { name: "Saint Martin", abbrv: "Saint-Martin" },
  { name: "San Marino", abbrv: "San-Marino" },
  { name: "Saudi Arabia", abbrv: "Saudi-Arabia" },
  { name: "Senegal", abbrv: "Senegal" },
  { name: "Serbia", abbrv: "Serbia" },
  { name: "Seychelles", abbrv: "Seychelles" },
  { name: "Singapore", abbrv: "Singapore" },
  { name: "Sint Maarten", abbrv: "Sint-Maarten" },
  { name: "Slovakia", abbrv: "Slovakia" },
  { name: "Slovenia", abbrv: "Slovenia" },
  { name: "Somalia", abbrv: "Somalia" },
  { name: "South Africa", abbrv: "South-Africa" },
  { name: "Spain", abbrv: "Spain" },
  { name: "Sri Lanka", abbrv: "Sri-Lanka" },
  { name: "St. Barth", abbrv: "St.-Barth" },
  { name: "St. Vincent Grenadines", abbrv: "St.-Vincent-Grenadines" },
  { name: "Sudan", abbrv: "Sudan" },
  { name: "Suriname", abbrv: "Suriname" },
  { name: "Sweden", abbrv: "Sweden" },
  { name: "Switzerland", abbrv: "Switzerland" },
  { name: "Taiwan", abbrv: "Taiwan" },
  { name: "Tanzania", abbrv: "Tanzania" },
  { name: "Thailand", abbrv: "Thailand" },
  { name: "Timor Leste", abbrv: "Timor-Leste" },
  { name: "Togo", abbrv: "Togo" },
  { name: "Trinidad and Tobago", abbrv: "Trinidad-and-Tobago" },
  { name: "Tunisia", abbrv: "Tunisia" },
  { name: "Turkey", abbrv: "Turkey" },
  { name: "U.S. Virgin Islands", abbrv: "U.S.-Virgin-Islands" },
  { name: "Uganda", abbrv: "Uganda" },
  { name: "Ukraine", abbrv: "Ukraine" },
  { name: "United Arab Emirates", abbrv: "UAE" },
  { name: "United Kingdom", abbrv: "UK" },
  { name: "United States of America", abbrv: "USA" },
  { name: "Uruguay", abbrv: "Uruguay" },
  { name: "Uzbekistan", abbrv: "Uzbekistan" },
  { name: "Vatican City", abbrv: "Vatican-City" },
  { name: "Venezuela", abbrv: "Venezuela" },
  { name: "Vietnam", abbrv: "Vietnam" },
  { name: "Zambia", abbrv: "Zambia" },
  { name: "Zimbabwe", abbrv: "Zimbabwe" },
];

export default countries;
